CREATE TABLE PERSONA (
    DNI VARCHAR2(9) PRIMARY KEY,
    NOM VARCHAR2(50),
    LLINATGES VARCHAR2(100),
    ADRECA VARCHAR2(100),
    CODI_POSTAL VARCHAR(5) CHECK (CODI_POSTAL != '07430'),
    TELEFON NUMBER(9),
    DATA_ALTA DATE
);
CREATE TABLE VEHICLE (
    MATRICULA VARCHAR2(7) PRIMARY KEY,
    MARCA VARCHAR2(30),
    MODEL_VEHICLE VARCHAR2(30),
    CHECK (SUBSTR(MODEL_VEHICLE, 1, 4) != 'RB19'),
    DNI VARCHAR2(9) NOT NULL,
    FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE MULTA (
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    DATA_I_HORA DATE,
    LLOC VARCHAR2(100),
    IMPORT_MULTA NUMBER(10,2) CHECK (IMPORT_MULTA >= 100.00),
    MATRICULA_VEHICLE VARCHAR2(7),
    FOREIGN KEY (MATRICULA_VEHICLE) REFERENCES VEHICLE(MATRICULA)
);

CREATE TABLE ACCIDENT (
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    LLOC VARCHAR2(100),
    DATA_I_HORA DATE
);

CREATE TABLE ACCIDENT_VEHICLE (
    MATRICULA_VEHICLE VARCHAR2(7) NOT NULL,
    CODI_ACCIDENT NUMBER NOT NULL,
    INFORME_PARTICIPACIO VARCHAR2(500),
    PRIMARY KEY (MATRICULA_VEHICLE, CODI_ACCIDENT),
    FOREIGN KEY (MATRICULA_VEHICLE) REFERENCES VEHICLE(MATRICULA),
    FOREIGN KEY (CODI_ACCIDENT) REFERENCES ACCIDENT(CODI)
);

    --INSERT INTO DE 2 persones.
    INSERT INTO PERSONA VALUES('41713034G','Ángel Cristian','López Torres','Carrer Felip II 2B','07010',644492911,TO_DATE('12-05-2025','DD-MM-YYYY'));
    INSERT INTO PERSONA VALUES('55061961F','Diego','Otin Milano','Carrer de Son Puig 10','07011',633386686,TO_DATE('20-04-2025','DD-MM-YYYY'));
    --INSERT INTO DE 3 vehicles, de manera que almenys 2 d'ells siguin de la mateixa persona.
    INSERT INTO VEHICLE VALUES('4872GYQ','Toyota','Aygo','41713034G');
    INSERT INTO VEHICLE VALUES('4113PQD','Porsche','911 Carrera','41713034G');
    INSERT INTO VEHICLE VALUES('5322QSE','Cupra','Formentor','55061961F');
    ----INSERT INTO DE Una multa posada a qualsevol vehicle existent.
    INSERT INTO MULTA(DATA_I_HORA,LLOC,IMPORT_MULTA,MATRICULA_VEHICLE) VALUES(TO_DATE('22-11-2024 11:59:24','DD-MM-YYYY HH24:MI:SS'),'Cami de Son Rapinya',200.00,'5322QSE' );
    ----INSERT INTO DE 1 accident que involucri almenys 2 vehicles (DE DIFERENTS PERSONES).
    INSERT INTO ACCIDENT(LLOC, DATA_I_HORA) VALUES('Poligono de Son Castello',TO_DATE('22-11-2024 18:29:24','DD-MM-YYYY HH24:MI:SS'));
    INSERT INTO ACCIDENT_VEHICLE VALUES('4872GYQ',1,'Giro hacia la izquierda sin mirar y chocaron');
    --Afegir una columna "data_pagament" com a data a MULTA.
    ALTER TABLE MULTA ADD DATA_PAGAMENT DATE;
    --Modificar "informe_participacio" de ACCIDENT_VEHICLE perquè la mida màxima del varchar2 sigui 2000
    ALTER TABLE ACCIDENT_VEHICLE MODIFY INFORME_PARTICIPACIO VARCHAR2(2000);
    --Eliminar la columna "data_alta" de persona.
    ALTER TABLE PERSONA DROP COLUMN DATA_ALTA;
    --Canviar el nom d'una persona per qualsevol altre (qualsevol, segons el DNI).
    UPDATE PERSONA SET NOM = 'Marcos' WHERE DNI = '41713034G';
    --Eliminar totes les multes d'un vehicle concret (qualsevol, segons la matrícula)
    DELETE FROM MULTA WHERE MATRICULA_VEHICLE = '5322QSE'