CREATE TABLE "TIPUS DE PLAZA"(
    NOM VARCHAR2(50) PRIMARY KEY,
    FUNCIO VARCHAR2(40) NOT NULL
);

CREATE TABLE PLAZA(
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    NOM VARCHAR2(30) NOT NULL,
    SALARI NUMBER(6) NOT NULL, --Existe la posibilidad de que pueda cobrar hasta 100.000 al mes
    "CODI PLAZA SUPERVISORA" NUMBER REFERENCES PLAZA(CODI),
    "INFORME SUPERVISIÓ" VARCHAR2(80), --No obligatorio
    "NOM TIPUS DE PLAZA" VARCHAR2(50) NOT NULL REFERENCES "TIPUS DE PLAZA"(NOM)
);


CREATE TABLE EMPLEAT(
    NSS NUMBER(12) PRIMARY KEY,
    NOM VARCHAR2(50) NOT NULL,
    LLINATGES VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100), --No obligatorio
    IBAN VARCHAR2(24) NOT NULL,
    CHECK(SUBSTR(IBAN,1,2) = 'ES'),
    CHECK(LENGTH(IBAN) = 24),--Porque el IBAN contiene letra ES y lo que se introduzca tiene que ser de 24 carácteres
    UNIQUE(IBAN)
);

CREATE TABLE OCUPA(
    "NSS EMPLEAT" NUMBER(12),
    "CODI PLAZA" NUMBER,
    "DATA INICI" DATE NOT NULL,
    "DATA FI" DATE , --No obligatorio
    PRIMARY KEY ("NSS EMPLEAT", "CODI PLAZA"),
    FOREIGN KEY ("NSS EMPLEAT") REFERENCES EMPLEAT(NSS),
    FOREIGN KEY ("CODI PLAZA") REFERENCES PLAZA(CODI)
);

CREATE TABLE NOMINA(
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    "IBAN PAGAMENT" VARCHAR(24) NOT NULL,
    IMPORT NUMBER(6,2) NOT NULL,
    "NSS EMPLEAT" NUMBER(12) NOT NULL REFERENCES EMPLEAT(NSS),
    "CODI PLAZA" NUMBER REFERENCES PLAZA(CODI),
    CHECK(SUBSTR("IBAN PAGAMENT",1,2) = 'ES'),
    CHECK(LENGTH("IBAN PAGAMENT") = 24)--Porque el IBAN contiene letra ES y lo que se introduzca tiene que ser de 24 carácteres
);

